name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Setup MySQL
      uses: mirromutth/mysql-action@v1.1
      with:
          host port: 3306
          container port: 3306
          mysql database: 'world' 
          mysql user: 'test'
          mysql password: '1234'
    - name: Build with Maven
      env:
          SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/world
          SPRING_DATASOURCE_USERNAME: 'test'
          SPRING_DATASOURCE_PASSWORD: '1234'
      run: mvn -B package --file pom.xml && cp target/*.war .

    - name: Create doc-app3 directory
      run: |
        mkdir -p doc-app3
        mv *.war doc-app3/ # WAR 파일을 doc-app3 디렉토리로 이동합니다.
        mv Dockerfile doc-app3/ # Dockerfile이 있다면 이동합니다.
        mv docker-compose.yml doc-app3/ # docker-compose.yml이 있다면 이동합니다.

    - name: Build Docker image
      run: |
        cd doc-app3 && docker build -t friend5hip/doc-app3:v1 .

    - name: Docker login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Docker Hub push
      run: docker push friend5hip/doc-app3:v1

    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: 43.200.170.100
        port: 22
        username: ubuntu
        key: ${{ secrets.PRIVATE_KEY }}
        script: |
          sudo docker container stop doc-app3
          sudo docker container rm doc-app3
          sudo docker rmi friend5hip/doc-app3:v1
          sudo docker pull friend5hip/doc-app3:v1
          cd doc-app3
          sudo docker-compose up -d
